### PR TITLE
Gemify bench9000 and better dir structure

### LINKED ISSUE #5: File organization
Benchmarks are currently under lib/, which is fairly surprising (lib/ should be only bench9000's own code).
Should they be in `bench/` or `benchmarks/` for clarity instead?

What about bench dependencies, should we move them to vendor/?
Having them in a subdirectory of the benchmarks builds funny paths like:
`[bench9000/lib/bench]/benchmarks/chunky_png/chunky_png/lib/chunky_png`

### PR DESCRIPTION
**Pull request by pitr-ch**
fix #5

### CODE REVIEW

**Comment by eregon** [comment]
Thanks for doing this!
The chunky/PSD benchmarks are now in benchmarks/chunky_png/benchmarks/*. The last benchmarks dir should be stripped as well.

**Comment by pitr-ch** [comment]
@eregon good idea, moved

**Comment by eregon** [comment]
looks good :+1:

**Comment by pitr-ch** [comment]
@chrisseaton The executable was renamed from `bench` to `bench9000` could that cause problems?

**Comment by chrisseaton** [comment]
If it does I'll fix it to use the new name.

**Pull request merged**
